version: '3'

services:
  ethe_bot:
    build:
      context: ..
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: eb_user
      POSTGRES_DB: ethe_bot_db
      POSTGRES_PASSWORD: ebuserpassword

volumes:
  postgres-data:
