version: '3'

services:
  bot:
    build:
      context: ..
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ..:/app
    depends_on:
      db:
          condition: service_healthy
    ports:
      - "8090:8090"

  db:
    image: postgres:latest
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U eb_user -d ethe_bot_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - ethe_bot_pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: eb_user
      POSTGRES_DB: ethe_bot_db
      POSTGRES_PASSWORD: ebuserpassword
    ports:
      - "5432:5432"


volumes:
  ethe_bot_pg_data:
